### ISSUE TITLE
Create subsytem for the arm

### ISSUE THREAD

**Issue by WesleyJ-128** [first95/FRC2023#6]
Create/finish the arm subsytem.  This should have the following interface:

- setPosition: moves the arm to any angular position, in degrees.  positive up, 0 at horizontal.
- getPosition: returns the current arm position
- toggle/set gripper: sets the claw to a state or toggles the gripper state.  Either is fine, and both options is better.
- getGripper: get the state (open/closed) of the gripper
- setPreset: moves the arm to any of 5 positions: handoff, stowed, score low, score mid, score high

setPreset should use an enum for preset positions.

**Comment by WesleyJ-128** [comment]
Arm subsystem should also publish arm position, in robot coordinates (meters, +X is forwards, +Y is left, +Z is up) to networkTables periodically.

**Comment by WesleyJ-128** [comment]
@zebragirl314  setPos() looks like it should work, as long as the motor controller parameters are initialized in the constructor.
This initialization should go in the constructor and begin with restoreFactoryDefaults() and end with burnFlash().

**Comment by zebragirl314** [comment]
I think this should be good. I'm moving on to commands
